"""Thickness Preview in Blender: geometry, refusals, and what it is not.

    blender -b --factory-startup --python tests/test_thickness_preview_blender.py

A THICKNESS PREVIEW is a visualization generated by offsetting the selected
Surface Interior along mesh-surface normals. It is NOT a physical simulation
and NOT a manufacturing model, and this suite is as interested in holding
that line as it is in the geometry.

What it checks, and why each one is here:

*   THE OFFSET IS THE THICKNESS ASKED FOR. Measured on a PLANAR fixture,
    where the right answer is known exactly rather than approximately: 10 mm
    must be 10 mm, and 30 mm must be 30 mm, to floating point.
*   THE SIDE WALL IS CONTINUOUS ACROSS CLIPPED TRIANGLES. The region border
    runs through triangle interiors, so the wall has to be built on the
    CLIPPED polygon edges. A wall built on whole-triangle edges would look
    almost right and be wrong exactly where the region's shape matters most.
*   IT IS BUILT FROM THE INTERIOR, NOT FROM A NEW ANALYSIS. Changing the
    thickness, the colour or the opacity rebuilds the preview geometry and
    touches neither the interior nor the boundary.
*   OUTWARD IS DETERMINED, NOT ASSUMED. On a closed component it comes from
    the signed volume. On an OPEN one there is no outward, and the preview is
    refused rather than quietly extruded into the body.
*   NOTHING UPSTREAM IS TOUCHED and NO SOLVER RUNS.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    import bpy
    from mathutils import Matrix, Vector
except ImportError:                                   # pragma: no cover
    print("SKIP  tests/test_thickness_preview_blender.py needs Blender:")
    print("      blender -b --factory-startup --python "
          "tests/test_thickness_preview_blender.py")
    raise SystemExit(0)

import numpy as np  # noqa: E402

FAILURES = []
CHECKS = [0]
SOLVER_CALLS = {"construct": 0}


def check(label, condition, detail=""):
    CHECKS[0] += 1
    if bool(condition):
        print("  PASS  %s" % label)
    else:
        FAILURES.append(label)
        print("  FAIL  %s %s" % (label, detail))


def instrument(exact_mmp):
    module = getattr(exact_mmp, "_geodesic", None)
    if module is None:
        return False
    original = module.PyGeodesicAlgorithmExact

    class Counted(object):
        def __init__(self, *args, **kwargs):
            SOLVER_CALLS["construct"] += 1
            self._inner = original(*args, **kwargs)

        def __getattr__(self, name):
            return getattr(self._inner, name)

    module.PyGeodesicAlgorithmExact = Counted
    return True


class NoSolver(object):
    def __init__(self, label):
        self.label = label

    def __enter__(self):
        self.before = SOLVER_CALLS["construct"]
        return self

    def __exit__(self, *exc):
        check("%s: pygeodesic was NEVER constructed" % self.label,
              SOLVER_CALLS["construct"] == self.before,
              "%d construction(s)" % (SOLVER_CALLS["construct"] - self.before))
        return False


def run(operator, **kwargs):
    try:
        return operator(**kwargs)
    except RuntimeError:
        return {'CANCELLED'}


def shell_gaps(obj, base_face_count):
    """Perpendicular distances between the base points and their offsets."""
    points = np.asarray([tuple(vertex.co) for vertex in obj.data.vertices],
                        dtype=np.float64)
    half = points.shape[0] // 2
    return np.linalg.norm(points[half:] - points[:half], axis=1)


def edge_use_counts(obj):
    uses = {}
    for polygon in obj.data.polygons:
        indices = list(polygon.vertices)
        count = len(indices)
        for index in range(count):
            a, b = indices[index], indices[(index + 1) % count]
            key = (a, b) if a < b else (b, a)
            uses[key] = uses.get(key, 0) + 1
    return uses


def main():
    import body_surface_measurement as bsmt
    bsmt.register()
    from body_surface_measurement import (geodesic, interior, landmarks,
                                          panelpreview, regions, state, viz,
                                          visualization)

    context = bpy.context
    props = context.scene.bsmt

    unavailable = geodesic.ensure_loaded()
    if unavailable:
        print("SKIP  the exact backend is unavailable: %s" % unavailable)
        raise SystemExit(0)
    check("pygeodesic is instrumented",
          instrument(geodesic.registry.exact_mmp))

    # ================================================================== A ==
    print("\nA. a CLOSED sphere: outward is defined, and the offset is exact")
    # A sphere rather than a flat patch, for two reasons. BSMT refuses a
    # geodesic on an exactly planar patch - the surface distance ties the
    # straight distance and float noise makes it a hair shorter, which its
    # invariant correctly calls impossible - so a flat fixture cannot carry a
    # boundary at all. And a planar fixture was never what made "10 mm is
    # 10 mm" meaningful: a normal offset moves every point exactly t along
    # its own unit normal, so the perpendicular GAP is exact on any surface.
    # What curvature breaks is the SHAPE, not the gap, and that is stated as
    # a limitation rather than tested as a number.
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    bpy.ops.mesh.primitive_uv_sphere_add(segments=48, ring_count=24,
                                         radius=100.0)
    sphere = context.object
    sphere.name = "Scan_BSMT"
    sphere.bsmt_scan.is_measurement_copy = True
    context.view_layer.objects.active = sphere
    bpy.ops.bsmt.diagnose_topology()
    canonical = geodesic.meshcache.get(context, sphere, props.unit,
                                       rebuild=True)
    faces = [tuple(int(value) for value in triangle)
             for triangle in canonical.triangles]
    check("A1: the fixture is CLOSED, so outward is defined",
          panelpreview.is_closed(faces))
    check("A2: and the signed volume gives outward, rather than the winding "
          "being assumed",
          panelpreview.outward_sign(canonical.vertices_local, faces) == 1.0,
          panelpreview.outward_sign(canonical.vertices_local, faces))

    landmark_collection = context.scene.bsmt_landmarks
    landmark_collection.clear()
    # Four landmarks spaced round a latitude band, which gives a SIMPLE loop.
    for index, triangle in enumerate((550, 2172, 1644, 1078), start=1):
        item = landmark_collection.add()
        item.stable_id = index
        item.protocol_id = "L%02d" % index
        item.name = "P%d" % index
        item.status = landmarks.STATUS_VALID
        point = item.surface_point
        point.triangle_index = int(triangle)
        point.barycentric = (1 / 3.0, 1 / 3.0, 1 / 3.0)
        point.source_object = sphere.name
        point.geometry_hash = canonical.geometry_hash
        point.component_id = canonical.component_of(triangle)
        point.valid = True
        point.status = "VALID"
    props.landmark_next_id = 5

    bpy.ops.bsmt.add_region()
    region = state.active_region(context, props)
    for index in range(4):
        props.landmark_index = index
        bpy.ops.bsmt.add_region_landmark()
    check("A3: the boundary computes",
          bpy.ops.bsmt.compute_region_boundary() == {'FINISHED'}
          and region.status == regions.STATUS_VALID, region.status_detail)
    solves = SOLVER_CALLS["construct"]

    # ================================================================== B ==
    print("\nB. the interior, and the preview built from it")
    with NoSolver("B"):
        check("B1: the interior computes",
              bpy.ops.bsmt.compute_region_interior() == {'FINISHED'}
              and region.interior_status == interior.STATUS_VALID,
              region.interior_detail)
        clipped = region.interior_partial_count
        check("B2: WITH clipped triangles, so the border runs through "
              "triangle interiors", clipped > 0, clipped)

        region.panel_thickness_mm = 10.0
        check("B3: Show Thickness Preview",
              bpy.ops.bsmt.show_region_panel() == {'FINISHED'},
              region.panel_detail)
        panel = visualization.region_panel(region.stable_id)
        check("B4: a preview helper exists", panel is not None)
        gaps = shell_gaps(panel, region.interior_full_count)
        # Tolerance is float32: the helper mesh stores coordinates at that
        # precision, so reading the gap back costs about 4e-6 mm on a
        # 100 mm sphere. The offset itself is computed in float64 and is
        # exact; this is the round trip through Blender's mesh, not the maths.
        check("B5: EVERY base point is offset by 10 mm, to the float32 the "
              "helper mesh is stored at (min %.6f, max %.6f)"
              % (gaps.min(), gaps.max()),
              abs(gaps.min() - 10.0) < 1e-4 and abs(gaps.max() - 10.0) < 1e-4,
              (gaps.min(), gaps.max()))

        region.panel_thickness_mm = 30.0
        bpy.ops.bsmt.show_region_panel()
        panel = visualization.region_panel(region.stable_id)
        gaps = shell_gaps(panel, region.interior_full_count)
        check("B6: and 30 mm is 30 mm (min %.6f, max %.6f)"
              % (gaps.min(), gaps.max()),
              abs(gaps.min() - 30.0) < 1e-4 and abs(gaps.max() - 30.0) < 1e-4,
              (gaps.min(), gaps.max()))

    # ================================================================== C ==
    print("\nC. OUTWARD, not inward")
    with NoSolver("C"):
        panel = visualization.region_panel(region.stable_id)
        points = np.asarray([tuple(vertex.co) for vertex in
                             panel.data.vertices], dtype=np.float64)
        half = points.shape[0] // 2
        base_radius = np.linalg.norm(points[:half], axis=1)
        outer_radius = np.linalg.norm(points[half:], axis=1)
        check("C1: every offset point is FURTHER from the centre than the "
              "point it came from - away from the body, not into it",
              bool((outer_radius > base_radius).all()),
              float((outer_radius - base_radius).min()))
        check("C2: by the thickness, radially (min %.3f, max %.3f)"
              % ((outer_radius - base_radius).min(),
                 (outer_radius - base_radius).max()),
              abs(float((outer_radius - base_radius).min()) - 30.0) < 0.5,
              float((outer_radius - base_radius).min()))
        check("C3: a convex surface offset outward folds nothing",
              region.panel_folded_faces == 0, region.panel_folded_faces)

    # ================================================================== D ==
    print("\nD. the side wall is CONTINUOUS around the clipped boundary")
    # The check this feature most needs. The region's border runs through
    # triangle interiors, so the wall has to be built on the CLIPPED polygon
    # edges. If it were built on whole-triangle edges the loop would be a
    # different length, would not close, or would leave the shell open.
    with NoSolver("D"):
        panel = visualization.region_panel(region.stable_id)
        uses = edge_use_counts(panel)
        open_edges = [key for key, value in uses.items() if value != 2]
        check("D1: the preview is CLOSED - every edge is used exactly twice, "
              "so the wall leaves no gap anywhere round the border",
              not open_edges, open_edges[:4])
        check("D2: which is only possible if the wall follows the clipped "
              "edges, because %d of the border's triangles are clipped"
              % clipped, clipped > 0)
        check("D3: the preview reports ONE boundary loop",
              "1 boundary loop" in region.panel_detail, region.panel_detail)
        wall = int(region.panel_detail.split("side-wall faces")[0]
                   .split(",")[-1].strip())
        check("D4: the wall has as many quads as the border has edges",
              wall > 0, wall)
        base = int(region.panel_detail.split("surface faces")[0]
                   .split(":")[-1].strip())
        check("D5: the base is the classified interior - one face per "
              "classified piece, clipped pieces included",
              base >= region.interior_full_count, (base,
                                                   region.interior_full_count))
        check("D6: the shell is base + outer + wall",
              len(panel.data.polygons) == 2 * base + wall,
              (len(panel.data.polygons), base, wall))

    # ================================================================== E ==
    print("\nE. thickness and colour rebuild the PREVIEW and nothing else")
    with NoSolver("E"):
        before = (region.interior_definition, region.interior_full_count,
                  region.interior_partial_count, region.cached_definition,
                  region.status, region.interior_status)
        fill_faces = len(visualization.region_fill(region.stable_id)
                         .data.polygons)
        for thickness in (5.0, 12.5, 25.0):
            region.panel_thickness_mm = thickness
            bpy.ops.bsmt.show_region_panel()
            gaps = shell_gaps(visualization.region_panel(region.stable_id),
                              region.interior_full_count)
            check("E1: %.1f mm gives a %.1f mm offset" % (thickness,
                                                          thickness),
                  abs(gaps.max() - thickness) < 1e-4, gaps.max())
        after = (region.interior_definition, region.interior_full_count,
                 region.interior_partial_count, region.cached_definition,
                 region.status, region.interior_status)
        check("E2: THE INTERIOR AND THE BOUNDARY ARE UNTOUCHED by every one "
              "of those", before == after, (before, after))
        check("E3: and so is the fill it was built from",
              len(visualization.region_fill(region.stable_id).data.polygons)
              == fill_faces)
        region.panel_color = (0.1, 0.9, 0.4, 1.0)
        region.panel_opacity = 0.8
        bpy.ops.bsmt.show_region_panel()
        check("E4: a colour and opacity change re-analyses nothing",
              (region.interior_definition, region.interior_full_count)
              == after[:2])

    # ================================================================== F ==
    print("\nF. an invalid thickness is refused, never quietly changed")
    with NoSolver("F"):
        for value, why in ((0.0, "zero"), (-5.0, "negative")):
            refused = None
            try:
                panelpreview.check_thickness(value)
            except panelpreview.PreviewError as exc:
                refused = exc
            check("F1: %s thickness is refused" % why, refused is not None)
            if refused is not None:
                check("F2: with a named reason (%s)" % why,
                      refused.code == panelpreview.CODE_BAD_THICKNESS,
                      refused.code)
        for value in (float("nan"), float("inf")):
            refused = None
            try:
                panelpreview.check_thickness(value)
            except panelpreview.PreviewError as exc:
                refused = exc
            check("F3: a non-finite thickness is refused",
                  refused is not None)
        refused = None
        try:
            panelpreview.check_thickness(5000.0)
        except panelpreview.PreviewError as exc:
            refused = exc
        check("F4: an absurd thickness is REFUSED, not clamped",
              refused is not None
              and "refuses rather than quietly" in refused.message,
              None if refused is None else refused.message[:60])
        check("F5: a sane thickness passes through unchanged",
              panelpreview.check_thickness(10.0) == 10.0)

    # ================================================================== G ==
    print("\nG. a rigid transform, and nothing upstream disturbed")
    with NoSolver("G"):
        region.panel_thickness_mm = 10.0
        bpy.ops.bsmt.show_region_panel()
        vertices_before = len(sphere.data.vertices)
        sphere.matrix_world = (Matrix.Translation(Vector((300.0, 50.0, -20.0)))
                             @ Matrix.Rotation(0.6, 4, 'Z'))
        context.view_layer.update()
        viz.sync_transforms(context, props)
        panel = visualization.region_panel(region.stable_id)
        check("G1: the preview followed the scan by matrix",
              all(abs(panel.matrix_world[r][c] - sphere.matrix_world[r][c])
                  < 1e-9 for r in range(4) for c in range(4)))
        gaps = shell_gaps(panel, region.interior_full_count)
        check("G2: and its thickness is unchanged by a move and a rotate",
              abs(gaps.max() - 10.0) < 1e-4, gaps.max())
        check("G3: the scan mesh is untouched",
              len(sphere.data.vertices) == vertices_before)
        check("G4: it is a BSMT helper, in the helper collection",
              visualization.is_helper(panel)
              and any(collection.name == visualization.COLLECTION_NAME
                      for collection in panel.users_collection))
        check("G5: and unselectable, so it cannot be picked on by mistake",
              panel.hide_select)

    # ================================================================== H ==
    print("\nH. a stale interior invalidates the preview")
    with NoSolver("H"):
        region.landmark_index = 1
        bpy.ops.bsmt.move_region_landmark(direction='DOWN')
        check("H1: reordering the landmarks makes the interior stale",
              region.interior_status == interior.STATUS_STALE,
              region.interior_status)
        check("H2: and the preview is REFUSED while it is",
              run(bpy.ops.bsmt.show_region_panel) == {'CANCELLED'})
        check("H3: the stale preview is removed rather than left looking "
              "solid and current",
              not visualization.region_panel_exists(region.stable_id))
        bpy.ops.bsmt.move_region_landmark(direction='UP')
        bpy.ops.bsmt.compute_region_interior()
        check("H4: recomputing the interior lets it be drawn again",
              bpy.ops.bsmt.show_region_panel() == {'FINISHED'})
        stable_id = int(region.stable_id)
        check("H5: Clear Previews keeps the interior and the fill",
              bpy.ops.bsmt.clear_region_panels() == {'FINISHED'}
              and not visualization.region_panel_exists(stable_id)
              and visualization.region_fill_exists(stable_id)
              and region.interior_status == interior.STATUS_VALID)
        bpy.ops.bsmt.show_region_panel()
        check("H6: deleting the region takes the preview with it",
              bpy.ops.bsmt.remove_region() == {'FINISHED'}
              and not visualization.region_panel_exists(stable_id))
        check("H7: and leaves every landmark and the scan alone",
              len(landmark_collection) == 4
              and bpy.data.objects.get("Scan_BSMT") is not None
              and len(bpy.data.objects["Scan_BSMT"].data.vertices)
              == vertices_before)

    # ================================================================== J ==
    print("\nJ. an OPEN surface has no outward, and the preview is refused")
    # Last, because it destroys the fixture. Opening the mesh also makes the
    # interior stale, so the end-to-end refusal could be for either reason -
    # the ORIENTATION POLICY itself is therefore checked directly, on the
    # opened mesh, which is the only way to see it rather than infer it.
    from body_surface_measurement import operators as bsmt_operators
    with NoSolver("J"):
        import bmesh
        mesh_data = sphere.data
        bm = bmesh.new()
        bm.from_mesh(mesh_data)
        bm.faces.ensure_lookup_table()
        doomed = [face for face in bm.faces
                  if face.calc_center_median().z < -95.0]
        bmesh.ops.delete(bm, geom=doomed, context='FACES')
        bm.to_mesh(mesh_data)
        bm.free()
        mesh_data.update()
        opened = geodesic.meshcache.get(context, sphere, props.unit,
                                        rebuild=True)
        open_faces = [tuple(int(value) for value in triangle)
                      for triangle in opened.triangles]
        check("J1: the fixture is now OPEN", len(doomed) > 0
              and not panelpreview.is_closed(open_faces), len(doomed))

        direction, why = bsmt_operators._outward_direction(
            opened, int(region.interior_component_id))
        check("J2: outward is REFUSED on it, not guessed", direction is None,
              direction)
        check("J3: saying the component is open and outward undefined",
              "OPEN" in why and "outward" in why, why[:90])
        check("J4: and that extruding inward would look right and be "
              "backwards", "backwards" in why, why[-70:])
        check("J5: a CLOSED component still resolves, so the policy is not "
              "simply refusing everything",
              panelpreview.outward_sign(
                  canonical.vertices_local,
                  [tuple(int(v) for v in t) for t in canonical.triangles])
              == 1.0)
        check("J6: and end to end the preview is refused",
              run(bpy.ops.bsmt.show_region_panel) == {'CANCELLED'})
        check("J7: with nothing drawn",
              not visualization.region_panel_exists(region.stable_id))

    # ================================================================== I ==
    print("\nI. what this is, stated where it cannot be missed")
    text = panelpreview.LIMITS
    check("I1: it says it is a VISUALIZATION", "VISUALIZATION" in text)
    check("I2: not a physical simulation",
          "not a physical simulation" in text)
    check("I3: and not a manufacturing model",
          "not a manufacturing model" in text)
    check("I4: it names the distortion - stretch and compression",
          "stretches" in text and "compresses" in text)
    check("I5: and the fold-through",
          "folds through itself" in text)
    check("I6: it says the material a real panel needs is NOT uniform",
          "is not" in text and "material" in text)
    check("I7: and that fold detection is a warning, not a guarantee",
          "not a guarantee" in text)
    check("I8: the solver was used only by Compute Boundary",
          SOLVER_CALLS["construct"] == solves, SOLVER_CALLS["construct"])
    check("I9: every NoSolver block passed",
          not [label for label in FAILURES if "NEVER constructed" in label],
          [label for label in FAILURES if "NEVER constructed" in label])

    print("\n%d checks, %d failure(s)" % (CHECKS[0], len(FAILURES)))
    for label in FAILURES:
        print("  FAILED: %s" % label)
    return 1 if FAILURES else 0


if __name__ == "__main__":
    code = 1
    try:
        code = main()
    finally:
        print("BSMT_THICKNESS_PREVIEW_RESULT=%d" % code)
    sys.exit(code)
