"""Thickness Preview: the selected Surface Interior, shown with a thickness.

    ordered landmarks -> cached closed boundary -> Surface Interior
                      -> THICKNESS PREVIEW
                      -> Surface Area [a later milestone]

A THICKNESS PREVIEW is a visualization generated by offsetting the selected
surface-region representation along mesh-surface normals. It is intended for
GEOMETRIC VISUALIZATION and is not a physical simulation or a manufacturing
model.

That sentence is the whole contract, and the rest of this module exists to
keep it honest.

What it is built from
---------------------
The classified interior, and nothing else. The base surface is exactly the
faces `interior.compute` produced - whole triangles and exactly-clipped
partial pieces - so the preview's footprint is the region's real footprint,
right up to where the boundary cuts through a triangle. Nothing is
re-analysed to draw it, and changing the thickness rebuilds only this
geometry.

What a normal offset actually does
----------------------------------
Every point is moved along its own surface normal by the same distance. On a
flat patch that is exactly a slab of that thickness. On a CURVED body it is
not:

* in a convex place the outer surface stretches, and the perpendicular gap
  between the two surfaces stays right while the spacing between neighbouring
  points grows;
* in a concave place it compresses, and once the thickness exceeds the local
  radius of curvature the outer surface FOLDS THROUGH ITSELF;
* so the Euclidean spacing between base and outer is uniform, but the
  material a real panel would need is not, and the outer surface is not a
  surface a fabricator could use as-is.

`fold_risk` reports where the second case is close, because it is cheap to
check and silently drawing a folded shell would be the worst kind of
plausible picture. It is a WARNING, not a proof of validity: a preview with
no reported risk may still be locally wrong.

Which way is out
----------------
"Outward" is a property of the solid, not of the surface, so it is determined
from the closed component's signed volume rather than assumed from the
winding. On a component that is NOT closed there is no solid, nothing defines
which side is out, and this module refuses rather than picking one - see
`ORIENTATION_UNDETERMINED`.

No bpy, no solver, and no geometry is modified anywhere.
"""

import numpy as np

#: Reason codes. Shared vocabulary with `interior`, not a parallel one.
CODE_NONE = ''
CODE_NO_INTERIOR = 'PANEL_NO_INTERIOR'
CODE_BAD_THICKNESS = 'PANEL_THICKNESS_INVALID'
CODE_ORIENTATION = 'PANEL_ORIENTATION_UNDETERMINED'
CODE_DEGENERATE = 'PANEL_DEGENERATE_SURFACE'

CODE_LABELS = {
    CODE_NO_INTERIOR: "there is no computed interior to give a thickness to",
    CODE_BAD_THICKNESS: "the thickness is not a usable positive length",
    CODE_ORIENTATION: "which way is outward cannot be determined",
    CODE_DEGENERATE: "the interior surface has no usable area",
}

#: Default preview thickness, in millimetres.
DEFAULT_THICKNESS_MM = 10.0

#: Thicknesses outside this are refused rather than clamped. A researcher who
#: types 500 mm has made a mistake worth telling them about, and silently
#: turning it into something else would hide it.
MIN_THICKNESS_MM = 0.01
MAX_THICKNESS_MM = 500.0

LIMITS = (
    "Thickness Preview offsets the classified interior along mesh-surface "
    "normals. It is a VISUALIZATION, not a physical simulation and not a "
    "manufacturing model. On a curved body a normal offset distorts: the "
    "outer surface stretches over convex areas and compresses over concave "
    "ones, and where the thickness exceeds the local radius of curvature it "
    "folds through itself. The perpendicular gap is uniform; the material a "
    "real panel would need is not. Fold risk is reported where it is cheap "
    "to detect, which is a warning and not a guarantee of validity."
)


class PreviewError(Exception):
    """A thickness preview cannot be built, with a reason code."""

    def __init__(self, code, message):
        super().__init__(message)
        self.code = code
        self.message = message


def check_thickness(value):
    """Validate a thickness in millimetres. Raises rather than clamping."""
    try:
        thickness = float(value)
    except (TypeError, ValueError):
        raise PreviewError(CODE_BAD_THICKNESS,
                           "the thickness is not a number")
    if not np.isfinite(thickness):
        raise PreviewError(CODE_BAD_THICKNESS,
                           "the thickness is not a finite number")
    if thickness <= 0.0:
        raise PreviewError(
            CODE_BAD_THICKNESS,
            "the thickness must be greater than zero - a panel with no "
            "thickness is the region itself, which Show Fill already draws")
    if thickness < MIN_THICKNESS_MM or thickness > MAX_THICKNESS_MM:
        raise PreviewError(
            CODE_BAD_THICKNESS,
            "the thickness must be between %.2f mm and %.0f mm; %.4g mm is "
            "outside that, and BSMT refuses rather than quietly using a "
            "different number" % (MIN_THICKNESS_MM, MAX_THICKNESS_MM,
                                  thickness))
    return thickness


# ---------------------------------------------------------------------------
# turning the drawn fill back into a connected patch
# ---------------------------------------------------------------------------
#
# The fill is built with its vertices duplicated per face, because that is
# what keeps two clipped pieces of one triangle apart for a later area sum.
# A shell needs the opposite: shared vertices, so a normal is the average of
# every face meeting there and the patch has a findable border.

def weld(points, faces, tolerance):
    """Merge coincident points. Returns (points, faces, original -> welded).

    Tolerance-based rather than exact. Two clipped pieces of neighbouring
    triangles meet at a boundary point both computed independently, so their
    coordinates agree to float precision and not to the bit - and a shell
    welded only on exact equality would split along every clipped edge,
    which is precisely where the side wall has to be continuous.
    """
    points = np.asarray(points, dtype=np.float64)
    if points.size == 0:
        return points, [], []
    quantum = float(tolerance)
    if quantum <= 0.0:
        quantum = 1e-9
    keys = np.round(points / quantum).astype(np.int64)

    lookup = {}
    mapping = np.empty(points.shape[0], dtype=np.int64)
    welded = []
    for index in range(points.shape[0]):
        key = (int(keys[index, 0]), int(keys[index, 1]), int(keys[index, 2]))
        found = lookup.get(key)
        if found is None:
            # Also look at the neighbouring cells: two points either side of
            # a cell wall are as close as two inside one, and missing them
            # would tear the patch exactly where welding matters most.
            for dx in (-1, 0, 1):
                for dy in (-1, 0, 1):
                    for dz in (-1, 0, 1):
                        other = lookup.get((key[0] + dx, key[1] + dy,
                                            key[2] + dz))
                        if other is not None and float(np.linalg.norm(
                                points[index] - welded[other])) <= quantum:
                            found = other
                            break
                    if found is not None:
                        break
                if found is not None:
                    break
        if found is None:
            found = len(welded)
            welded.append(points[index])
            lookup[key] = found
        mapping[index] = found

    out_faces = []
    for face in faces:
        remapped = []
        for index in face:
            value = int(mapping[index])
            if not remapped or remapped[-1] != value:
                remapped.append(value)
        while len(remapped) > 1 and remapped[0] == remapped[-1]:
            remapped.pop()
        if len(remapped) >= 3:
            out_faces.append(tuple(remapped))
    return np.asarray(welded, dtype=np.float64), out_faces, mapping


def boundary_loops(faces):
    """Ordered vertex loops round the border of a welded patch.

    A border edge is one used by exactly ONE face. On the interior patch
    those are precisely the edges the region boundary runs along - including
    the chords through clipped triangles - so the loops returned here are
    what the side wall is built on, and the wall is continuous across a
    clipped triangle for the same reason the patch is.
    """
    uses = {}
    for face in faces:
        count = len(face)
        for index in range(count):
            a, b = face[index], face[(index + 1) % count]
            key = (a, b) if a < b else (b, a)
            uses[key] = uses.get(key, 0) + 1

    # Directed border edges, keeping each face's own winding so the wall is
    # built the same way round as the surface it hangs from.
    directed = {}
    for face in faces:
        count = len(face)
        for index in range(count):
            a, b = face[index], face[(index + 1) % count]
            key = (a, b) if a < b else (b, a)
            if uses.get(key) == 1:
                directed.setdefault(a, []).append(b)

    loops = []
    remaining = {a: list(bs) for a, bs in directed.items()}
    while remaining:
        start = next(iter(remaining))
        loop = [start]
        node = start
        while True:
            options = remaining.get(node)
            if not options:
                break
            following = options.pop()
            if not options:
                remaining.pop(node, None)
            if following == start:
                break
            if following in loop:
                break
            loop.append(following)
            node = following
        if len(loop) >= 3:
            loops.append(loop)
    return loops


def vertex_normals(points, faces):
    """Area-weighted vertex normals. Zero where a vertex has no usable area."""
    normals = np.zeros_like(points)
    for face in faces:
        corners = points[list(face)]
        accumulated = np.zeros(3)
        origin = corners[0]
        for index in range(1, corners.shape[0] - 1):
            accumulated = accumulated + np.cross(corners[index] - origin,
                                                 corners[index + 1] - origin)
        # Not normalised: the cross product's magnitude IS twice the area, so
        # a big face pulls a shared normal round more than a sliver does.
        for index in face:
            normals[index] = normals[index] + accumulated
    lengths = np.linalg.norm(normals, axis=1)
    usable = lengths > 0.0
    normals[usable] = normals[usable] / lengths[usable][:, None]
    return normals, usable


def outward_sign(points, faces):
    """+1 or -1 for which way the face winding points, or None.

    Determined from the SIGNED VOLUME of the closed surface, not assumed from
    the winding: outward is a property of the solid, and a surface that does
    not enclose one has no outward. `points`/`faces` here are the WHOLE
    component, not the region - a patch encloses nothing.
    """
    total = 0.0
    for face in faces:
        corners = points[list(face)]
        origin = corners[0]
        for index in range(1, corners.shape[0] - 1):
            total += float(np.dot(origin,
                                  np.cross(corners[index], corners[index + 1])))
    volume = total / 6.0
    scale = float(np.linalg.norm(points.max(axis=0) - points.min(axis=0)))
    if scale <= 0.0 or abs(volume) < 1e-9 * scale ** 3:
        return None
    return 1.0 if volume > 0.0 else -1.0


def is_closed(faces):
    """Does every edge of this face set have exactly two users?"""
    uses = {}
    for face in faces:
        count = len(face)
        for index in range(count):
            a, b = face[index], face[(index + 1) % count]
            key = (a, b) if a < b else (b, a)
            uses[key] = uses.get(key, 0) + 1
    return bool(uses) and all(value == 2 for value in uses.values())


# ---------------------------------------------------------------------------
# the shell
# ---------------------------------------------------------------------------

def fold_risk(points, normals, faces, thickness):
    """Faces where the offset is near or past the local radius of curvature.

    Cheap and local: a face whose offset copy has flipped over, or shrunk to
    almost nothing, is a face where the outer surface has folded. Reported as
    a WARNING - it catches the obvious cases, and a preview it says nothing
    about may still be locally wrong.
    """
    flipped = 0
    for face in faces:
        indices = list(face)
        base = points[indices]
        moved = base + normals[indices] * thickness
        before = _face_normal(base)
        after = _face_normal(moved)
        if before is None or after is None:
            flipped += 1
            continue
        if float(before.dot(after)) <= 0.0:
            flipped += 1
    return flipped


def _face_normal(corners):
    origin = corners[0]
    accumulated = np.zeros(3)
    for index in range(1, corners.shape[0] - 1):
        accumulated = accumulated + np.cross(corners[index] - origin,
                                             corners[index + 1] - origin)
    length = float(np.linalg.norm(accumulated))
    return None if length <= 0.0 else accumulated / length


def build_shell(points, faces, thickness, direction, tolerance):
    """The preview: base surface, offset outer surface, and the side wall.

    Returns a dict with the shell geometry and what was measured building it.
    `direction` is +1 or -1 and is applied to the vertex normals, so the
    caller decides outward once and this never guesses.

    The shell is closed on a patch whose border is a set of loops: every
    border edge gets a quad joining base to outer, so the preview reads as a
    solid from the side rather than as two floating sheets.
    """
    points, faces, _mapping = weld(points, faces, tolerance)
    if points.size == 0 or not faces:
        raise PreviewError(CODE_DEGENERATE,
                           "the interior surface has no usable faces")

    normals, usable = vertex_normals(points, faces)
    if not bool(usable.all()):
        raise PreviewError(
            CODE_DEGENERATE,
            "%d point(s) of the interior have no surface normal, so there is "
            "no direction to offset them along" % int((~usable).sum()))

    offset = normals * (float(thickness) * float(direction))
    outer = points + offset

    loops = boundary_loops(faces)
    if not loops:
        raise PreviewError(
            CODE_DEGENERATE,
            "the interior has no border, so there is nothing to build a side "
            "wall on")

    count = points.shape[0]
    shell_points = np.vstack([points, outer])
    shell_faces = []
    # Base, winding reversed so it faces away from the outer surface - the
    # preview should read as a solid from either side.
    for face in faces:
        shell_faces.append(tuple(reversed([int(index) for index in face])))
    for face in faces:
        shell_faces.append(tuple(int(index) + count for index in face))

    wall_faces = 0
    for loop in loops:
        length = len(loop)
        for index in range(length):
            a = int(loop[index])
            b = int(loop[(index + 1) % length])
            shell_faces.append((a, b, b + count, a + count))
            wall_faces += 1

    return {
        "points": shell_points,
        "faces": shell_faces,
        "base_face_count": len(faces),
        "wall_face_count": wall_faces,
        "loop_count": len(loops),
        "loop_lengths": [len(loop) for loop in loops],
        "vertex_count": int(shell_points.shape[0]),
        "folded_faces": fold_risk(points, normals * float(direction), faces,
                                  float(thickness)),
        "limits": LIMITS,
    }
